<?php
/**
 * Plugin Name:       D²nAI Radar Intrants
 * Description:       AI event-radar on raw-material prices (sulfur first). Buyers maintain an editable watchlist and get a sourced, directional buy/price signal generated by the AI Lab LLM (Open WebUI / OpenAI-compatible). Calls go through a server-side proxy, so the API key never reaches the browser and there is no CORS.
 * Version:           1.0.0
 * Author:            D²nAI · OCP Nutricrops
 * License:           GPL-2.0-or-later
 * Text Domain:       dnai-radar
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

define( 'DNAI_RADAR_VER', '1.0.0' );
define( 'DNAI_RADAR_URL', plugin_dir_url( __FILE__ ) );

/* -------------------------------------------------------------------------
 * 1. System prompt
 * ---------------------------------------------------------------------- */
function dnai_radar_default_prompt() {
	return <<<'EOT'
RÔLE
Tu es "Radar Soufre", analyste de veille marché pour OCP Nutricrops (équipe D²nAI). Tu surveilles le marché mondial du SOUFRE et émets un signal directionnel argumenté sur le risque d'évolution de son prix, pour les acheteurs et la direction.

MÉTHODE (IMPÉRATIVE)
1. Utilise la recherche web pour récupérer des informations RÉCENTES (priorité aux 14 derniers jours). N'utilise jamais un prix ou un fait de mémoire : tout chiffre et toute affirmation doivent venir d'une source récupérée et CITÉE.
2. Distingue le FAIT (sourcé) de ton INTERPRÉTATION (analyse).
3. Le "niveau de confiance" est un avis d'analyste raisonné, PAS une probabilité statistique. Si l'info est mince, dis confiance Faible.
4. Si tu ne trouves pas d'info fiable, dis-le plutôt que d'inventer.

FORMAT DE SORTIE (toujours respecter, exactement ces lignes)
📅 Date : <date>
🧪 Matière : Soufre
📈 Signal : <↑ Hausse | ↓ Baisse | → Stable>
⏳ Horizon : court terme (0–3 mois)
🎚️ Confiance : <Faible | Moyenne | Élevée>
💲 Prix de référence connu : <valeur + date + source>

🔑 Facteurs clés (3 à 5, chacun avec sa source) :
- …

🧭 Lecture analyste :
<2–4 phrases : pourquoi ce signal, ce qui pourrait l'invalider>

🛒 Implication achat :
<fenêtre d'achat / temporiser / constituer du stock — prudent et argumenté>

🔗 Sources :
<liste des liens cités>
EOT;
}

/* -------------------------------------------------------------------------
 * 2. Settings
 * ---------------------------------------------------------------------- */
function dnai_radar_opt( $key, $default = '' ) {
	$o = get_option( 'dnai_radar_settings', array() );
	return isset( $o[ $key ] ) && $o[ $key ] !== '' ? $o[ $key ] : $default;
}

add_action( 'admin_menu', function () {
	add_options_page( 'D²nAI Radar', 'D²nAI Radar', 'manage_options', 'dnai-radar', 'dnai_radar_settings_page' );
} );

add_action( 'admin_init', function () {
	register_setting( 'dnai_radar', 'dnai_radar_settings', array( 'sanitize_callback' => 'dnai_radar_sanitize' ) );
} );

function dnai_radar_sanitize( $in ) {
	return array(
		'base_url'      => isset( $in['base_url'] ) ? esc_url_raw( trim( $in['base_url'] ) ) : '',
		'api_path'      => isset( $in['api_path'] ) ? sanitize_text_field( $in['api_path'] ) : '/api/chat/completions',
		'api_key'       => isset( $in['api_key'] ) ? trim( $in['api_key'] ) : '',
		'model'         => isset( $in['model'] ) ? sanitize_text_field( $in['model'] ) : 'radar-soufre',
		'web_search'    => ! empty( $in['web_search'] ) ? '1' : '',
		'system_prompt' => isset( $in['system_prompt'] ) ? sanitize_textarea_field( $in['system_prompt'] ) : '',
	);
}

function dnai_radar_settings_page() {
	$base   = dnai_radar_opt( 'base_url', 'https://lab.ocpnutricrops.ai' );
	$path   = dnai_radar_opt( 'api_path', '/api/chat/completions' );
	$key    = dnai_radar_opt( 'api_key', '' );
	$model  = dnai_radar_opt( 'model', 'radar-soufre' );
	$web    = dnai_radar_opt( 'web_search', '1' );
	$prompt = dnai_radar_opt( 'system_prompt', dnai_radar_default_prompt() );
	?>
	<div class="wrap">
		<h1>D²nAI Radar Intrants — settings</h1>
		<p>Connect the AI Lab LLM (Open WebUI / OpenAI-compatible). Add the radar to any page with the shortcode <code>[dnai_radar]</code>. The API key stays server-side (the browser calls the WP REST proxy <code>/wp-json/dnai-radar/v1/signal</code>).</p>
		<form method="post" action="options.php">
			<?php settings_fields( 'dnai_radar' ); ?>
			<table class="form-table" role="presentation">
				<tr><th><label>AI Lab base URL</label></th>
					<td><input type="url" name="dnai_radar_settings[base_url]" value="<?php echo esc_attr( $base ); ?>" class="regular-text" placeholder="https://lab.ocpnutricrops.ai">
					<p class="description">Open WebUI host (no trailing slash).</p></td></tr>
				<tr><th><label>API path</label></th>
					<td><input type="text" name="dnai_radar_settings[api_path]" value="<?php echo esc_attr( $path ); ?>" class="regular-text">
					<p class="description">OpenAI-compatible chat endpoint. Open WebUI default: <code>/api/chat/completions</code></p></td></tr>
				<tr><th><label>API key</label></th>
					<td><input type="password" name="dnai_radar_settings[api_key]" value="<?php echo esc_attr( $key ); ?>" class="regular-text" autocomplete="off">
					<p class="description">Open WebUI → Settings → Account → API Keys. Stored server-side, never exposed to the browser.</p></td></tr>
				<tr><th><label>Radar model</label></th>
					<td><input type="text" name="dnai_radar_settings[model]" value="<?php echo esc_attr( $model ); ?>" class="regular-text" placeholder="radar-soufre">
					<p class="description">Your <code>radar-soufre</code> model (with web search + Perplexity) or <code>GPT-OSS</code>.</p></td></tr>
				<tr><th><label>Web search</label></th>
					<td><label><input type="checkbox" name="dnai_radar_settings[web_search]" value="1" <?php checked( $web, '1' ); ?>> Force web search on the request</label>
					<p class="description">Sends <code>features.web_search=true</code> so the model browses live sources. Disable if your model already searches by default.</p></td></tr>
				<tr><th><label>System prompt</label></th>
					<td><textarea name="dnai_radar_settings[system_prompt]" rows="16" class="large-text code"><?php echo esc_textarea( $prompt ); ?></textarea>
					<p class="description">Drives the analyst role, method and output format of the radar.</p></td></tr>
			</table>
			<?php submit_button(); ?>
		</form>
	</div>
	<?php
}

/* -------------------------------------------------------------------------
 * 3. REST proxy — keeps the API key server-side, avoids CORS
 * ---------------------------------------------------------------------- */
add_action( 'rest_api_init', function () {
	register_rest_route( 'dnai-radar/v1', '/signal', array(
		'methods'             => 'POST',
		'callback'            => 'dnai_radar_rest_signal',
		'permission_callback' => function ( $request ) {
			return (bool) wp_verify_nonce( $request->get_header( 'X-WP-Nonce' ), 'wp_rest' );
		},
	) );
} );

function dnai_radar_rest_signal( WP_REST_Request $request ) {
	$base  = dnai_radar_opt( 'base_url' );
	$path  = dnai_radar_opt( 'api_path', '/api/chat/completions' );
	$key   = dnai_radar_opt( 'api_key' );
	$model = dnai_radar_opt( 'model', 'radar-soufre' );
	$web   = dnai_radar_opt( 'web_search', '1' ) === '1';
	if ( ! $base || ! $key ) {
		return new WP_REST_Response( array( 'error' => 'not_configured', 'message' => 'Radar not configured. Set base URL, API key and model in Settings → D²nAI Radar.' ), 503 );
	}

	$watchlist = $request->get_param( 'watchlist' );
	$watchlist = is_string( $watchlist ) ? mb_substr( wp_strip_all_tags( $watchlist ), 0, 4000 ) : '';

	$today = date_i18n( 'l j F Y' );
	$user  = "Watchlist actuelle à surveiller en priorité :\n" . $watchlist .
		"\n\nNous sommes le " . $today . ". Génère le radar soufre de cette semaine en respectant exactement le format demandé.";

	$payload = array(
		'model'    => $model,
		'messages' => array(
			array( 'role' => 'system', 'content' => dnai_radar_opt( 'system_prompt', dnai_radar_default_prompt() ) ),
			array( 'role' => 'user',   'content' => $user ),
		),
		'stream'   => false,
	);
	if ( $web ) {
		$payload['features'] = array( 'web_search' => true );
	}

	$resp = wp_remote_post( rtrim( $base, '/' ) . $path, array(
		'timeout' => 90,
		'headers' => array(
			'Authorization' => 'Bearer ' . $key,
			'Content-Type'  => 'application/json',
		),
		'body'    => wp_json_encode( $payload ),
	) );

	if ( is_wp_error( $resp ) ) {
		return new WP_REST_Response( array( 'error' => 'AI Lab unreachable: ' . $resp->get_error_message() ), 502 );
	}
	$code = wp_remote_retrieve_response_code( $resp );
	$body = json_decode( wp_remote_retrieve_body( $resp ), true );
	if ( $code >= 400 || empty( $body['choices'][0]['message']['content'] ) ) {
		$msg = isset( $body['error']['message'] ) ? $body['error']['message'] : ( 'AI Lab error (HTTP ' . $code . ')' );
		return new WP_REST_Response( array( 'error' => $msg ), 502 );
	}

	return new WP_REST_Response( array( 'reply' => $body['choices'][0]['message']['content'] ), 200 );
}

/* -------------------------------------------------------------------------
 * 4. Assets
 * ---------------------------------------------------------------------- */
add_action( 'wp_enqueue_scripts', function () {
	wp_register_style( 'dnai-radar', DNAI_RADAR_URL . 'assets/dnai-radar.css', array(), DNAI_RADAR_VER );
	wp_register_script( 'dnai-radar', DNAI_RADAR_URL . 'assets/dnai-radar.js', array(), DNAI_RADAR_VER, true );
	wp_localize_script( 'dnai-radar', 'DNAI_RADAR', array(
		'rest'  => esc_url_raw( rest_url( 'dnai-radar/v1' ) ),
		'nonce' => wp_create_nonce( 'wp_rest' ),
	) );
} );

/* -------------------------------------------------------------------------
 * 5. Shortcode  [dnai_radar]
 * ---------------------------------------------------------------------- */
function dnai_radar_shortcode( $atts ) {
	wp_enqueue_style( 'dnai-radar' );
	wp_enqueue_script( 'dnai-radar' );
	$a = shortcode_atts( array(
		'title'    => 'Radar Intrants',
		'material' => 'Soufre',
	), $atts );
	ob_start(); ?>
	<div class="dnai-radar" data-material="<?php echo esc_attr( $a['material'] ); ?>">
		<div class="dnai-radar-head">
			<div class="dnai-radar-kicker">Veille marché matières premières · D²nAI</div>
			<h2 class="dnai-radar-title"><?php echo esc_html( $a['title'] ); ?></h2>
			<p class="dnai-radar-intro">L'IA surveille l'actualité géopolitique, logistique et marché, puis émet un signal directionnel argumenté et sourcé sur le prix de vos intrants. Vous alimentez la watchlist, l'IA fait la veille.</p>
		</div>

		<div class="dnai-radar-grid">
			<div class="dnai-radar-panel">
				<div class="dnai-radar-matrow">
					<span class="dnai-radar-lab">Matière suivie</span>
					<span class="dnai-radar-mat"><span class="dnai-radar-mi"><?php echo esc_html( mb_substr( $a['material'], 0, 1 ) ); ?></span> <?php echo esc_html( $a['material'] ); ?></span>
				</div>

				<button type="button" class="dnai-radar-gen" id="dnai-radar-gen">
					<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2 3 14h9l-1 8 10-12h-9z"/></svg>
					Générer le radar de la semaine
				</button>

				<div class="dnai-radar-think" id="dnai-radar-think">
					<span class="dnai-radar-matrix"></span>
					<span>Balayage des sources d'actualité &amp; analyse de la watchlist…</span>
				</div>

				<div class="dnai-radar-signal" id="dnai-radar-signal">
					<div class="dnai-radar-sigtop">
						<div class="dnai-radar-dir" id="dnai-radar-dir">→</div>
						<div class="dnai-radar-sigmeta">
							<div class="dnai-radar-l1" id="dnai-radar-date">—</div>
							<div class="dnai-radar-l2" id="dnai-radar-sigtitle"><?php echo esc_html( $a['material'] ); ?></div>
						</div>
						<span class="dnai-radar-conf" id="dnai-radar-conf">—</span>
					</div>
					<div class="dnai-radar-body" id="dnai-radar-bodytext"></div>
					<div class="dnai-radar-actions">
						<button type="button" class="dnai-radar-mini" id="dnai-radar-copy">Copier</button>
						<button type="button" class="dnai-radar-mini" id="dnai-radar-regen">Régénérer</button>
					</div>
				</div>

				<div class="dnai-radar-disc">
					Signal indicatif d'aide à la décision, fondé sur un avis d'analyste IA raisonné — ce n'est pas une prévision de prix garantie. Le niveau de confiance reflète la qualité des sources, pas une probabilité statistique. Vérifiez toujours les sources citées.
				</div>

				<div class="dnai-radar-hist">
					<div class="dnai-radar-histlab">Historique des signaux · track record <span class="dnai-radar-clear" id="dnai-radar-clear">Effacer</span></div>
					<div id="dnai-radar-histlist"></div>
				</div>
			</div>

			<div class="dnai-radar-panel dnai-radar-aside">
				<h3 class="dnai-radar-wltitle">Watchlist</h3>
				<p class="dnai-radar-wlsub">Ce que l'IA surveille en priorité. Ajoutez vos fournisseurs, ports, événements à suivre.</p>
				<div id="dnai-radar-watchlist"></div>
				<form class="dnai-radar-addform" id="dnai-radar-addform">
					<select id="dnai-radar-addcat"></select>
					<input id="dnai-radar-addlabel" placeholder="Ex. Détroit d'Ormuz, Tengiz, embargo…" maxlength="80" required>
					<button type="submit">+ Ajouter à la watchlist</button>
				</form>
				<div class="dnai-radar-wlfoot"><a id="dnai-radar-reset">↺ Réinitialiser la liste de départ</a></div>
			</div>
		</div>
	</div>
	<?php return ob_get_clean();
}
add_shortcode( 'dnai_radar', 'dnai_radar_shortcode' );
